### ISSUE TITLE
Can't fold directories on linux

### ISSUE THREAD

**Issue by ochen** [mpl/xplor#5]
I noticed that there are different line addresses for `darwin` and other platforms. Not so familiar with the sam language, but I tried modifying them and found that the `darwin` ones will work on linux.

**Comment by mpl** [comment]
it's funny, I wrote xplor while I was on linux, so the "old" addresses (the non-darwin case) certainly used to work. Then I switched to darwin and noticed that folding didn't work anymore, which is why I added the new case. But rather than an OS difference (which would indeed be odd), it's probably that something changed in the sam lang implementation between the time I initially wrote xplor and the time I switched to darwin.
Thanks for telling me, I will fix.
